"""
proj7k.lazer - Subsystem for osu!lazer client.realm integration, non-destructive ingestion,
and background synchronization.
"""

from proj7k.lazer.bridge import (
    RealmBridgeClient,
    LazerBeatmapRecord,
    BeatmapUpdatePayload,
    BeatmapRevertPayload,
    BatchUpdateResult,
    BridgeEnvironmentStatus,
)
from proj7k.lazer.annotator import (
    INJECTED_SUFFIX_PATTERN,
    BINNED_TAG_PATTERN,
    TECHNIQUE_TITLE_MAP,
    TECHNIQUE_COLLECTIONS,
    TIER_COLLECTIONS,
    ALL_BIAXIAL_COLLECTIONS,
    BeatmapCollectionEntry,
    format_dominant_title,
    strip_injected_suffix,
    format_injected_difficulty_name,
    generate_binned_skill_tags,
    strip_binned_skill_tags,
    inject_binned_skill_tags,
    get_technique_collection_name,
    get_tier_collection_name,
    get_beatmap_biaxial_collections,
    build_biaxial_collection_map,
    annotate_lazer_beatmap,
    create_lazer_revert_payload,
    annotate_batch_and_build_collections,
)
from proj7k.lazer.lock import (
    LockBusyError,
    probe_realm_lock,
    SafeFlushWindow,
)
from proj7k.lazer.backup import (
    DEFAULT_CACHE_DIR,
    DEFAULT_BACKUP_STATE_FILE,
    BeatmapBackupState,
    LazerBackupManager,
)
from proj7k.lazer.daemon import (
    DEFAULT_FILES_DIR,
    DEFAULT_LOCK_PATH,
    SyncOptions,
    SyncSummary,
    resolve_beatmap_file,
    LazerSyncManager,
    LazerDaemon,
    run_daemon,
)

__all__ = [
    "RealmBridgeClient",
    "LazerBeatmapRecord",
    "BeatmapUpdatePayload",
    "BeatmapRevertPayload",
    "BatchUpdateResult",
    "BridgeEnvironmentStatus",
    "INJECTED_SUFFIX_PATTERN",
    "BINNED_TAG_PATTERN",
    "TECHNIQUE_TITLE_MAP",
    "TECHNIQUE_COLLECTIONS",
    "TIER_COLLECTIONS",
    "ALL_BIAXIAL_COLLECTIONS",
    "BeatmapCollectionEntry",
    "format_dominant_title",
    "strip_injected_suffix",
    "format_injected_difficulty_name",
    "generate_binned_skill_tags",
    "strip_binned_skill_tags",
    "inject_binned_skill_tags",
    "get_technique_collection_name",
    "get_tier_collection_name",
    "get_beatmap_biaxial_collections",
    "build_biaxial_collection_map",
    "annotate_lazer_beatmap",
    "create_lazer_revert_payload",
    "annotate_batch_and_build_collections",
    "LockBusyError",
    "probe_realm_lock",
    "SafeFlushWindow",
    "DEFAULT_CACHE_DIR",
    "DEFAULT_BACKUP_STATE_FILE",
    "BeatmapBackupState",
    "LazerBackupManager",
    "DEFAULT_FILES_DIR",
    "DEFAULT_LOCK_PATH",
    "SyncOptions",
    "SyncSummary",
    "resolve_beatmap_file",
    "LazerSyncManager",
    "LazerDaemon",
    "run_daemon",
]

